<a href="https://colab.research.google.com/github/MVFran/MorphometricsNeuralNetwork/blob/master/PyTorchForDeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensores

Un tensor es una "matriz multidimensional" que contiene elementos de un solo tipo de dato.

Es similar a los arreglos de Numpy, pero con más cosas que se pueden hacer, trabajan mejor con el uso de GPU.

Por defecto son del tipo Float32

Son más adecuados para Deep Learning que los arreglos de Numpy

In [2]:
import torch
import numpy as np

In [4]:
np1 = np.random.rand(3,4)
np1 # En este caso se tiene un arreglo de numpy

array([[0.28939585, 0.00996123, 0.76874708, 0.09069429],
       [0.93400275, 0.43442337, 0.73551807, 0.72836532],
       [0.25546472, 0.61055429, 0.40873429, 0.23002203]])

In [5]:
tensor2d = torch.randn(3, 4)
tensor2d # Se tiene un arreglo de pytorch

tensor([[ 0.3698, -1.7258,  0.5869, -0.4710],
        [-0.0938,  2.6747,  1.0882, -0.6824],
        [-0.4247,  0.3542, -0.0386,  0.2582]])

In [6]:
tensor3d = torch.zeros(2, 3, 4)
tensor3d # En este caso, se tiene un tensor de 3 dimensiones

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
# Podemos crear un tensor a partir de un arreglo de numpy
numpy_tensor = torch.tensor(np1)
numpy_tensor  # Los arreglos de numpy son float64 mientras que los tensores son float32, por eso aparece al final el dtype del nuevo tensor

tensor([[0.2894, 0.0100, 0.7687, 0.0907],
        [0.9340, 0.4344, 0.7355, 0.7284],
        [0.2555, 0.6106, 0.4087, 0.2300]], dtype=torch.float64)

## Operaciones con tensores

In [12]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Podemos modificar las dimensiones del tensor
my_torch.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
# Debe haber consistencia con las dimensiones iniciales ya que si no la hay arroja un error
my_torch.reshape(2,6)

RuntimeError: shape '[2, 6]' is invalid for input of size 10

In [18]:
# También podemos redimensionar si no sabemos exactamente las dimensiones del tensor con el argumento -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
my_torch2.reshape(3, -1)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [23]:
# Podemos hacer lo mismo con el primer argumento
my_torch3 = torch.arange(12)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
my_torch3.reshape(-1, 6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [26]:
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
my_torch4.view(2,5)  # view es similar a reshape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
# Con reshape y view el tensor original se actualiza
my_torch6 = torch.arange(10)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
my_torch7 = my_torch6.reshape(2, 5)
my_torch7

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
my_torch6[1] = 555
my_torch6

tensor([  0, 555,   2,   3,   4,   5,   6,   7,   8,   9])

In [32]:
my_torch7 # Aunque no se ejecutó nuevamente la celda donde se definió my_torch7, el valor se actualizó

tensor([[  0, 555,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [34]:
# Para tomar un item especifico se realiza lo mismo que usualmente se hace en python
my_torch8 = torch.arange(10)
my_torch8[6]  # Observemos que el resultado no es un valor sino que también es del tipo tensor

tensor(6)

In [39]:
my_torch8 = my_torch8.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [41]:
my_torch8[:,1] # En este caso selecciona sólo la segunda columna y devuelve un tensor unidimensional.

tensor([1, 3, 5, 7, 9])

In [42]:
my_torch8[:, 1:] # Selecciona desde la segunda columna hasta el final y devuelve un tensor bidimensional.

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

## Operaciones matemáticas con tensores

